/// <reference types="node" />

/**
 * Turns Natural Earth's public-domain TopoJSON into a plain list of SVG path
 * strings, keyed by ISO 3166-1 numeric code.
 *
 * Run with: pnpm map:generate
 *
 * d3-geo, topojson-client and world-atlas are dev dependencies used only here.
 * The browser receives nothing but the generated strings.
 */
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { geoEqualEarth, geoPath } from 'd3-geo'
import { feature } from 'topojson-client'
import type { FeatureCollection, Geometry } from 'geojson'
import type { Topology } from 'topojson-specification'

const require = createRequire(import.meta.url)
const here = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(here, '../src/components/map/world-paths.generated.ts')

const WIDTH = 1000
const PRECISION = 1

const topology = require('world-atlas/countries-110m.json') as Topology
const countries = feature(
  topology,
  topology.objects.countries,
) as unknown as FeatureCollection<Geometry, { name: string }>

const projection = geoEqualEarth()
projection.fitWidth(WIDTH, { type: 'Sphere' })

const bounds = geoPath(projection).bounds({ type: 'Sphere' } as never)
const height = Math.ceil(bounds[1][1])
const path = geoPath(projection)

const round = (d: string) =>
  d.replace(/-?\d+\.\d+/g, (match) => String(Number(Number(match).toFixed(PRECISION))))

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'unknown'

const entries = countries.features
  .map((item) => {
    const d = path(item)
    if (!d) return null
    const name = item.properties?.name ?? ''
    // Some Natural Earth features (Kosovo, N. Cyprus, Somaliland) have no ISO id.
    const id = item.id != null && String(item.id) !== 'undefined' ? String(item.id) : slugify(name)
    return { id, name, d: round(d) }
  })
  .filter((item): item is { id: string; name: string; d: string } => item !== null)
  .sort((a, b) => a.name.localeCompare(b.name))

const spherePath = round(path({ type: 'Sphere' } as never) ?? '')

const file = `// Generated by scripts/generate-world-map.mts — do not edit by hand.
// Source: Natural Earth via the world-atlas package (public domain),
// projected with d3-geo's Equal Earth projection.

export type WorldCountryPath = {
  /** ISO 3166-1 numeric code, matching the \`isoNumeric\` field on a country. */
  id: string
  name: string
  d: string
}

export const WORLD_VIEWBOX = { width: ${WIDTH}, height: ${height} } as const

export const WORLD_SPHERE_PATH = '${spherePath}'

export const WORLD_COUNTRY_PATHS: WorldCountryPath[] = ${JSON.stringify(entries, null, 2)}
`

await mkdir(dirname(outFile), { recursive: true })
await writeFile(outFile, file, 'utf8')

const kb = Math.round(Buffer.byteLength(file) / 1024)
console.log(`Wrote ${entries.length} country paths (${kb} kB) to ${outFile}`)
